development:
  adapter: postgresql
  database: torquebox_development
  username: torquebox
  password: torquebox
  host: localhost
  encoding: UTF8
 
production:
  adapter: postgresql
  database: torquebox_production
  username: torquebox
  password: torquebox
  host: localhost
  encoding: UTF8